version: "2.21"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/grocery.sql:/grocery.sql
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    env_file:
      - .env

  web:
    build: ./
    command: python ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    image: sales-forecasting:cp3

  worker:
    command: celery -A grocery_sales_forecasting_web worker --loglevel=INFO -Q train,infer
    depends_on:
      - db
      - web
      - redis
    env_file:
      - .env
    image: sales-forecasting:cp3
