version: "2.21"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:15.0
    ports:
      - 8000:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/grocery.sql:/grocery.sql
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    env_file:
      - .env

  model:
    build: ./
    command: celery -A tasks worker --loglevel=INFO -Q train,infer
    depends_on:
      - db
      - redis
    env_file:
      - .env
    image: sales-forecasting:cp3
