paths:
      sells: 'data/sells.parquet'
      models: 'models'
      predictions: 'data/predictions'

constants:
      predicting_unit: 'unit_id'
      date_col: 'date'
      horizont: 7
      raw_target: 'unit_sales'

feature_generation:
      rolling_windows: [7, 14, 21]

modeling:
      target: 'target_07'
      drop_columns: ['unit_id', 'date', 'target', 'year', 'month', 'dayofweek', 'day', 'dayofyear', 'week']

sql:
  tables_creation_queries_path: './sql/create_tables'
