mlflow:
      logging: False
      logging_uri: "http://127.0.0.1:8080"
      experiment_name: "CatBoostRegressor"
      tag_name: "2000_iterations_6_depth"
      tag_value: "Basic catboost model."
      artifact_path: "ts_model_2000_6"
      registered_model_name: "catboost-2000-6-ts"
